# Compilador y flags
CXX = g++
CXXFLAGS = -std=c++17 -O2 -Wall

# Archivos fuente y objeto
SRC = main.cpp mergesort.cpp quicksort.cpp utils.cpp
OBJ = $(SRC:.cpp=.o)

# Ejecutable
TARGET = sort_externo

# Regla por defecto
all: $(TARGET)

# Enlazado
$(TARGET): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^

# Regla para compilar archivos .cpp a .o
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Limpiar archivos generados
clean:
	rm -f $(OBJ) $(TARGET)
